id: P000317
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:42.405468
source_metadata:
  id: bdr:W923
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བརྒལ་ལན།
  author: ''
  volumes:
    b15d3b305d39457b8728c2492c383a42:
      image_group_id: I1KG8924
      title: Volume 1 of drang nges legs bshad snying po'i brgal lan
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
