id: opecha:P000317
initial_creation_type: ocr
source_metadata:
  id: bdr:W923
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བརྒལ་ལན།
  volume:
    b15d3b305d39457b8728c2492c383a42:
      image_group_id: I1KG8924
      title: Volume 1 of drang nges legs bshad snying po'i brgal lan
      volume_number: 1
      total_pages: 118
  author: ''
ebook_metadata:
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་བརྒལ་ལན།
  author: ''
  sku: P000317
  cover: cover.jpg
  layers:
  - pagination
